name: Block Unconventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webiny/action-conventional-commits@v1.3.1
